trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-8
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 20
    maxParallelTrials: 2
    hyperparameterMetricTag: F1
    params:
    - parameterName: max-depth
      type: INTEGER
      minValue: 4
      maxValue: 20
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: min-samples-split
      type: DOUBLE
      minValue: 0.001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: max-features
      type: CATEGORICAL
      categoricalValues: ['sqrt', '0.25', '0.5', '0.75']
    - parameterName: max-samples
      type: DOUBLE
      minValue: 0.1
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE